### ISSUE TITLE
Format of valid files?

### ISSUE THREAD

**Issue by orcudy** [off-by-one/propositional-inference#1]
I have a file named cnf.txt containing the following:

(not A) (B) (C)
(not C) (D)
(not D) (Q)

When I run `(print-knowledge (make-inferences (read-kbdb "cnf.txt")))`, I get the following error: 

_CAR: A is not a list_

What is the input file suppose to look like? Am I doing something wrong?

**Comment by off-by-one** [comment]
Yeah, those instructions are wrong. To use your example, the file's contents should be

((not A) (B) (C))
((not C) (D))
((not D) (Q))
